name: Testing deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        sudo apt install python3-setuptools
        sudo pip3 install conan
        sed -i "s/checkout('v' + self.version)/checkout('${{ github.sha }}')/" conanfile.py
        conan export . dronmdf/testing
        conan remote add pureoop https://api.bintray.com/conan/mdf/pureoop
        conan user -p ${{ secrets.BINTRAY }} -r pureoop dronmdf
        conan upload "*" -r pureoop --confirm

