name: Testing deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        sudo apt install python3-setuptools
        sudo pip3 install conan
        sed -i "s/checkout('v' + self.version)/checkout('${{ github.sha }}')/" conanfile.py
        conan export . dronmdf/testing
        conan remote add pureoop-2out https://conan.cloudsmith.io/pureoop/2out
        conan user -p ${{ secrets.CLOUDSMITH }} -r pureoop-2out andrey-valyaev
        conan upload "*" -r pureoop-2out --confirm

